// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeDBApi.Models;

#nullable disable

namespace RecipeDBApi.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20240227083918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RecipeDBApi.Models.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IngredientSublistId")
                        .HasColumnType("bigint");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IngredientSublistId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeDBApi.Models.IngredientSublist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<long>("RecipeVersionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecipeVersionId");

                    b.ToTable("IngredientSublists");
                });

            modelBuilder.Entity("RecipeDBApi.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeDBApi.Models.RecipeVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CookingInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.Property<int>("PreparationInMinutes")
                        .HasColumnType("int");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeVersions");
                });

            modelBuilder.Entity("RecipeDBApi.Models.Ingredient", b =>
                {
                    b.HasOne("RecipeDBApi.Models.IngredientSublist", "IngredientSublist")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientSublistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientSublist");
                });

            modelBuilder.Entity("RecipeDBApi.Models.IngredientSublist", b =>
                {
                    b.HasOne("RecipeDBApi.Models.RecipeVersion", "RecipeVersion")
                        .WithMany("IngredientSublists")
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeVersion");
                });

            modelBuilder.Entity("RecipeDBApi.Models.RecipeVersion", b =>
                {
                    b.HasOne("RecipeDBApi.Models.Recipe", "Recipe")
                        .WithMany("RecipeVersions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeDBApi.Models.IngredientSublist", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RecipeDBApi.Models.Recipe", b =>
                {
                    b.Navigation("RecipeVersions");
                });

            modelBuilder.Entity("RecipeDBApi.Models.RecipeVersion", b =>
                {
                    b.Navigation("IngredientSublists");
                });
#pragma warning restore 612, 618
        }
    }
}
